---
apiVersion: v1
kind: Template
labels:
  template: zap-template
message: A zap container has been created in your project.
metadata:
  annotations:
    iconClass: icon-openshift
    description: "zap template"
    tags: instant-app
  name: "zap"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${NAME}"
      deploymentConfig: "${NAME}"
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    replicas: 1
    selector:
      app: "${NAME}"
      deploymentConfig: "${NAME}"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: "${NAME}"
          deploymentConfig: "${NAME}"
      spec:
        containers:
        - name: "${NAME}"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
            requests:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl http://localhost:8080/JSON/core/view/mode/
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "zap:latest"
    - type: ConfigChange
parameters:
- description: The name of the OpenShift Service exposed for the Zap container.
  displayName: Zap App Name
  name: NAME
  required: true
- description: The memory limit for the Zap container.
  displayName: Zap Memory Limit
  name: MEMORY_LIMIT
  value: 2Gi